# Growth
“Indeed, the entire cell can be viewed as a factory that contains an elaborate network of interlocking assembly lines, each of which is composed of a set of large protein machines.”
- Bruce Alberts @alberts1998

Diffusion
## Caulobacter crescentus

The life of a cell is simple in theory, and complex in practice. The evolutionary purpose of your cell is to grow, amassing enough resources to eventually multiply itself. How best to grow, though, depends on the environment and what fuel is available. In a world of scarce resources and fierce competition, any adaptation that lets your cell grow more efficiently can have a big effect on its success. Often these adaptations are visible in the structure of the cell, as you will see in this chapter.

You have already seen how the shape of your cell can allow it to gather nutrients from the environment more efficiently. For example, prosthecate bacteria like this *Caulobacter crescentus* use long, thin extensions to increase surface area relative to volume, allowing them to absorb more nutrients. The extra surface area of a stalk increases a cell's ability to absorb nutrients, but it also adds more membrane, diluting membrane proteins and increasing the time it takes them to diffuse around the cell. *C. crescentus* stalks get longer throughout their lifetime, so the situation only gets worse with age. To solve this problem, you might want to separate the envelope of the stalk from the envelope of the rest of the cell. *C. crescentus* has evolved a structure to do this, called a stalk band. These protein structures form diffusion barriers for the membranes and periplasm, but not the cytoplasm., so nutrients can still diffuse into the cell body. Each cell division produces another band in the elongating stalk, so you can tell a cell's divisional age by counting its bands.




Anaerobic Respiration
```{R echo=FALSE, screenshot.alt='img/4_1_Ccrescentus.jpg' , fig.cap= 'Caulobacter crescentus Collected by: Zhuo Li [10.22002/D1.1489](https://doi.org/10.22002/D1.1489)'}
library(doivideo)
doivideo('10.22002/D1.1489',0)
```

## Shewanella oneidensis

Other cell extensions also aid metabolism. Non-photosynthetic cells break down nutrients into chemical energy (ATP) through respiration reactions. The chemistry is beyond our scope here, but it involves the ultimate transfer of electrons to an acceptor molecule, typically oxygen (the "aer" in aerobic respiration). When no oxygen is present, some cells can use an alternative electron acceptor, such as iron or sulfur, in a process called anaerobic respiration. This works well when the acceptor is soluble and can diffuse into the cell. You can see deposits of soluble metal on the membrane of this *Shewanella oneidensis* cell which it is likely using for anaerobic respiration.

What if the only available acceptor is trapped in a mineral, though? *S. oneidensis* have evolved a mechanism to take their metabolism to the mineral by extending chains of outer membrane vesicles. Electron-carrying proteins in the membrane shuttle electrons to metal oxide minerals in the environment, a conductive property that lends the appendages the name "nanowires." The morphology of *S. oneidensis* nanowires is similar to that of other outer membrane vesicle chains, with tubular and pearled sections, like the detached nanowire you see here.

Other species, like *Geobacter sulfurreducens*, also use nanowires to transfer electrons to an insoluble acceptor in the environment, but the structure of those nanowires is very different: a long filament made from stacked cytochrome proteins, resembling a pilus (thin protein filaments you will see in Chapters 6 and 9).






Photosynthesis
```{R echo=FALSE, screenshot.alt='img/4_2_Soneidensis.jpg' , fig.cap= 'Shewanella oneidensis Collected by: Poorna Subramanian [10.22002/D1.1490](https://doi.org/10.22002/D1.1490)'}
library(doivideo)
doivideo('10.22002/D1.1490',0)
```

## Rhodopseudomonas palustris

Photosynthetic bacteria harvest energy from sunlight using protein complexes [Schematic–Photocomplexes] embedded in their membrane. An easy way to increase the light-gathering capability of such a cell would be to expand the membrane, but then the cell's volume would also increase. To get around this problem, why not stack the extra membrane inside the cell? Many (but not all) photosynthetic bacteria contain intracytoplasmic membrane, or ICM. In cells like this *Rhodopseudomonas palustris*, the ICM is continuous with the inner membrane, forming stacks at the middle of the cell. These stacks grow and shrink as needed depending on light conditions and the cell’s metabolic state. Different species have different, and more extensive, arrangements [More–ICM variety].

```{R echo=FALSE, screenshot.alt='img/4_3_Rpalustris.jpg' , fig.cap= 'Rhodopseudomonas palustris Collected by: Alasdair McDowall [10.22002/D1.1491](https://doi.org/10.22002/D1.1491)'}
library(doivideo)
doivideo('10.22002/D1.1491',0)
```

## 3[Schematic: Photocomplexes]
Light-harvesting photocomplexes can comprise hundreds of individual proteins and reach tens of nanometers in size, as you can see in this complex from a red alga (the machinery is closely related to that found in cyanobacteria) @ma2020. Physically tethering enzymes that function in the same pathway increases efficiency by allowing enzymes that catalyze subsequent steps to hand off substrates. You will see more examples of this theme in the following pages; metabolic enzymes in the cell often cluster together into relay teams.

```{R echo=FALSE, screenshot.alt='img/4_4_Chloroflexi.jpg' , fig.cap= 'Chloroflexi Collected by: Elitza Tocheva [10.22002/D1.1492](https://doi.org/10.22002/D1.1492)'}
library(doivideo)
doivideo('10.22002/D1.1492',0)
```

### Methyloprofundus sedimenti {#ICM_variety}In some species, like this *Methyloprofundus sedimenti*, the intracytoplasmic membrane is very extensive and appears to be fully separated from the cell membrane. As you can see, it occupies much of the cytoplasmic space.



Photosynthesis (cont’d.)
```{R echo=FALSE, screenshot.alt='img/4_3a_Msedimenti.jpg' , fig.cap= 'Methyloprofundus sedimenti Collected by: Elitza Tocheva [10.22002/D1.1499](https://doi.org/10.22002/D1.1499)'}
library(doivideo)
doivideo('10.22002/D1.1499',0)
```

## Chloroflexi

Other photosynthetic bacteria have taken the specialization of their light-harvesting membranes a step further, expanding not the entire membrane, but simply the hydrophobic interior. The result is a sort of factory called a chlorosome. These structures consist of up to hundreds of thousands of photocomplexes packed tightly inside a lipid monolayer. The size and shape varies between species, from wide lozenges to the thin, curved rod in this *Chloroflexi* cell. They are often tethered close to the membrane (and thus the light), and may be so abundant as to form a nearly continuous layer around the cell. As with intracytoplasmic membrane, their production is controlled in response to need. Chlorosomes, and other compartments you will see soon, challenge the idea that organelles exist only in eukaryotes.





Enzyme Regulation
```{R echo=FALSE, screenshot.alt='img/4_4_Chloroflexi.jpg' , fig.cap= 'Chloroflexi Collected by: Elitza Tocheva [10.22002/D1.1492](https://doi.org/10.22002/D1.1492)'}
library(doivideo)
doivideo('10.22002/D1.1492',0)
```

## Clostridium thermocellum

Cells are subject to the vagaries of an environment in which conditions often change. To respond, they must be metabolically agile. The production of enzymes is dialed up and down to meet demand, but they can also be regulated in other ways. Degrading and resynthesizing proteins wastes resources and time. So why not just furlough workers when demand lags and call them back in when things pick up again? Cells across all domains of life have evolved an elegant furlough mechanism: enzyme polymerization. You already saw an example of this in Chapter 3: the metabolic enzyme CTP synthase. Another example is the alcohol-acetaldehyde dehydrogenase (AdhE) enzymes that allow *Clostridium thermocellum* like this one to digest cellulose into ethanol. As you can see, AdhE polymerizes into helical filaments called spirosomes. Polymerization can either inactivate an enzyme (e.g. by occluding its active site), or activate it (e.g. by changing its conformation to open an active site). For AdhE, it seems to do both; it is thought that spirosomes torque from a compact, inactive form to a more extended, active form (what you see here) [Schematic–AdhE spirosome structure]. Whatever the details, polymerization is a rapid way to mobilize (or demobilize) a large number of enzymes for a metabolic task.

Furloughed workers can also be recruited to other projects. Remember that CTP synthase filaments play a secondary, cytoskeletal role. (And perhaps many, if not all, cytoskeletal elements evolved this way.) AdhE spirosomes seem to have a secondary function in cell adhesion, although the details are not yet clear.

```{R echo=FALSE, screenshot.alt='img/4_5_Cthermocellum.jpg' , fig.cap= 'Clostridium thermocellum Collected by: Elitza Tocheva [10.22002/D1.1493](https://doi.org/10.22002/D1.1493)'}
library(doivideo)
doivideo('10.22002/D1.1493',0)
```

## 5[Schematic–AdhE spirosome structure]




Microcompartments
```{R echo=FALSE, screenshot.alt='img/4_4_Chloroflexi.jpg' , fig.cap= 'Chloroflexi Collected by: Elitza Tocheva [10.22002/D1.1492](https://doi.org/10.22002/D1.1492)'}
library(doivideo)
doivideo('10.22002/D1.1492',0)
```

## Acetonema longum

In addition to increasing the number of active workers to boost metabolic output, you could also make them more efficient. One way to do this is by bringing enzymes that work in the same pathway together into an assembly (or disassembly) line. Such factories are common inside cells. You could even go a step further and enclose the factory in a dedicated building. These buildings, found in bacteria but not (as far as we know) archaea, are known as microcompartments–areas of the cytoplasm walled off by a protein shell [Schematic–Microcompartment shells]. For instance, *Acetonema longum* like this use a factory called the propanediol utilization, or pdu, microcompartment to increase the efficiency of an enzymatic pathway that breaks down 1,2-propanediol. Illustrating the interlocking lives of microbial communities, 1,2-propanediol is itself the byproduct of the metabolism of other microbes, neighbors in *A. longum*’s environment in the gut of an animal.



```{R echo=FALSE, screenshot.alt='img/4_6_Alongum.jpg' , fig.cap= 'Acetonema longum Collected by: Elitza Tocheva [10.22002/D1.1494](https://doi.org/10.22002/D1.1494)'}
library(doivideo)
doivideo('10.22002/D1.1494',0)
```

## 6[Schematic–Microcompartment shells]
Bacterial microcompartments are typically enclosed by a self-assembling shell formed by just a few proteins. The shell is icosahedral, consisting of hexameric units packed into flat planes, which are joined together by pentamers at the vertices. You can see this arrangement in the shell structure of a microcompartment called an encapsulin that helps *Thermotoga maritima* respond to stress @sutter2008.


Carboxysomes
```{R echo=FALSE, screenshot.alt='img/4_4_Chloroflexi.jpg' , fig.cap= 'Chloroflexi Collected by: Elitza Tocheva [10.22002/D1.1492](https://doi.org/10.22002/D1.1492)'}
library(doivideo)
doivideo('10.22002/D1.1492',0)
```

## Thiomonas intermedia

One of the most impressive bacterial microcompartments is the carboxysome that some species use for carbon fixation (the breakdown of carbon dioxide into usable fuel molecules). Carboxysomes contain tightly packed copies of an enzyme called ribulose bisphosphate carboxylase/oxygenase, or more simply, RuBisCO, which, incidentally, is the most abundant enzyme on Earth. In this case, the shell does more than simply concentrate the enzymes. Oxygen competes with carbon dioxide for binding RuBisCO, so the bacteria include another enzyme in the compartment which converts bicarbonate into CO2, increasing the local concentration and making it readily available to the RuBisCO. The shell may also slow down the diffusion of CO2 out, and O2 in. Carboxysomes were probably unnecessary in early cells because the oxygen level of the environment was much lower. Cells, like this *Thiomonas intermedia*, can contain many carboxysomes. While most are icosahedral, there is significant variation in their forms [More–Carboxysome variety] [More–Long carboxysomes].

In this case, the microcompartment protects its contents from the rest of the cell, but they can also do the reverse. Some metabolic pathways generate toxic intermediates, and bacteria have evolved microcompartments to sequester them so that they do not interfere with other processes in the cell.


```{R echo=FALSE, screenshot.alt='img/4_7_Tintermedia.jpg' , fig.cap= 'Thiomonas intermedia Collected by: Cristina Iancu [10.22002/D1.1495](https://doi.org/10.22002/D1.1495)'}
library(doivideo)
doivideo('10.22002/D1.1495',0)
```

### Halothiobacillus neapolitanus {#Carboxysome_variety}Most carboxysomes look like the ones you saw on the last page, but not all. Some are less regular polyhedra, as in this *Halothiobacillus neapolitanus* cell. And some are stranger still [More–Long carboxysomes].

```{R echo=FALSE, screenshot.alt='img/4_7a_Hneapolitanus.jpg' , fig.cap= 'Halothiobacillus neapolitanus Collected by: Cristina Iancu [10.22002/D1.1500](https://doi.org/10.22002/D1.1500)'}
library(doivideo)
doivideo('10.22002/D1.1500',0)
```

### Hydrogenovibrio crunogenus {#Long_carboxysomes}The carboxysomes in this *Hydrogenovibrio crunogenus* have grown abnormally long, extending across the full width of the cell. These are unusual, but less dramatic elongations are common.

This cell also highlights the lability in the outer membrane common in some bacterial species, particularly pathogens. Note how the cell has curled inside its loose outer membrane. You can also see part of it stretching across to another cell in a neighboring hole; they were probably just finishing division when they were pulled apart by sample preparation.


Storage
```{R echo=FALSE, screenshot.alt='img/4_7b_Hcrunogenus.jpg' , fig.cap= 'Hydrogenovibrio crunogenus Collected by: Cristina Iancu [10.22002/D1.1501](https://doi.org/10.22002/D1.1501)'}
library(doivideo)
doivideo('10.22002/D1.1501',0)
```

## Cupriavidus necator

No matter how efficient your factories are, they need raw materials, and in an ever-changing environment, a cell cannot always depend upon a steady supply chain. How can you help your cell cope with occasional shortages? If you said stockpile, you are in good agreement with Nature. Both bacteria and archaea use storage granules to stockpile essential nutrients. The substrate is usually polymerized for easier packing, like poly-phosphate or the poly-hydroxybutyrate (a carbon store) in these *Cupriavidus necator* granules. No matter what they pack, storage granules are generally spherical, and exhibit a range of sizes [More–Storage granule growth]. When the environment is rich in one nutrient but poor in another, cells may stop growing, but keep adding to their cellular stores. You can see that effect in this C. necator cell which has been cultured in a medium with carbon but not enough nitrogen; as a result, it has accumulated very large poly-hydroxybutyrate granules which take up much of the cytoplasmic space.

Storage granules are ubiquitous in bacteria, and you will see them in many of the cells in this book. The most common type is poly-phosphate, which has a characteristic dark appearance in electron microscopy images.

```{R echo=FALSE, screenshot.alt='img/4_8_Cnecator.jpg' , fig.cap= 'Cupriavidus necator Collected by: Morgan Beeby [10.22002/D1.1496](https://doi.org/10.22002/D1.1496)'}
library(doivideo)
doivideo('10.22002/D1.1496',0)
```

### Lysobacter antibioticus {#Storage_granule_growth}Storage granules expand and contract to accommodate their contents. This *Lysobacter antibioticus* cell exhibits a typical range of sizes of poly-phosphate granules.





Storage (cont’d.)
```{R echo=FALSE, screenshot.alt='img/4_8a_Lantibioticus.jpg' , fig.cap= 'Lysobacter antibioticus Collected by: Morgan Beeby [10.22002/D1.1502](https://doi.org/10.22002/D1.1502)'}
library(doivideo)
doivideo('10.22002/D1.1502',0)
```

## Agrobacterium tumefaciens

Some types of storage granules, like poly-phosphate and poly-hydroxybutyrate, are very densely packed and clearly delineated from the rest of the cytoplasm. Others are less tightly packed and more amorphous, like the ones in this *Agrobacterium tumefaciens* cell. We do not yet know what these contain.

In some species, like the *Cupriavidus necator* on the last page, storage granules seem to be positioned randomly in the cell. Other species have more regulated arrangements. *A. tumefaciens* cells always have one poly-phosphate storage granule located near the cell pole. Other species have one at each end of the cell. As we will discuss in Chapter 5, this arrangement can help mother cells deliver a storage granule to each of their daughters during division.

You might expect a close relationship between cellular factories and storage depots. In fact, there does seem to be a relationship between carboxysomes and storage granules, although the details remain unclear [More–Granule-containing carboxysomes] [More–Carboxysome-granule connections].




```{R echo=FALSE, screenshot.alt='img/4_9_Atumefaciens.jpg' , fig.cap= 'Agrobacterium tumefaciens Collected by: Elitza Tocheva [10.22002/D1.1497](https://doi.org/10.22002/D1.1497)'}
library(doivideo)
doivideo('10.22002/D1.1497',0)
```

### Hydrogenovibrio crunogenus {#Granule-containing_carboxysomes}Small poly-phosphate storage granules are sometimes seen *inside* carboxysomes, as in this *Hydrogenovibrio crunogenus* cell. Their purpose is unknown.


```{R echo=FALSE, screenshot.alt='img/4_9a_Hcrunogenus.jpg' , fig.cap= 'Hydrogenovibrio crunogenus Collected by: Cristina Iancu [10.22002/D1.1503](https://doi.org/10.22002/D1.1503)'}
library(doivideo)
doivideo('10.22002/D1.1503',0)
```

### Halothiobacillus neapolitanus {#Carboxysomes-granule_connections}We sometimes see comb-like structures connecting external poly-phosphate storage granules with carboxysomes, as in this *Halothiobacillus neapolitanus* cell. The nature of the relationship between the structures, and the identity and function of the combs, remains a mystery.





Archaeal Storage Granules
```{R echo=FALSE, screenshot.alt='img/4_9b_Hneapolitanus.jpg' , fig.cap= 'Halothiobacillus neapolitanus Collected by: Cristina Iancu [10.22002/D1.1504](https://doi.org/10.22002/D1.1504)'}
library(doivideo)
doivideo('10.22002/D1.1504',0)
```

## Halorubrum litoreum

Archaea also use storage granules, and you will see many examples throughout the book. Compared to the typically-smooth edges of bacterial granules, the edges of many archaeal granules are spikier, giving them a rougher appearance, as in this *Halorubrum litoreum* cell. Others are smooth and, just like in bacteria, they exhibit a range of morphologies depending on what they store. For instance, compare [More–Haloferax gibbonsii granules] and [More–Halohasta litchfieldiae granules].




10a_Haloferax gibbonsii More: Haloferax gibbonsii granules
Some archaeal cells, like this *Haloferax gibbonsii*, contain many small granules. We do not yet know what they store, but it may be a carbon source.


10b_Halohasta litchfieldiae More: Halohasta litchfieldiae granules
This *Halohasta litchfieldiae* cell has more unusual granules. The high electron-density (darkness) of these punctate structures suggests that they contain metal.









References



Further Reading

@barry2011
@hoppert1999
@kerfeld2018
@oostergetel2010
```{R echo=FALSE, screenshot.alt='img/4_10_Hlitoreum.jpg' , fig.cap= 'Halorubrum litoreum Collected by: Ariane Briegel [10.22002/D1.1498](https://doi.org/10.22002/D1.1498)'}
library(doivideo)
doivideo('10.22002/D1.1498',0)
```

