# (APPENDIX) Appendix {-} 

# Feature Index 

Click on a feature in the sidebar to see examples in different species.

## AdhE spirosomes {-}

Clostridium thermocellum \@ref(fig:4-5)


## Adhesion complexes and filaments {-}

Flavobacterium johnsoniae \@ref(fig:6-11)

Mycoplasma genitalium \@ref(fig:2-1)

Mycoplasma pneumoniae \@ref(fig:6-12)


## Archaella {-}

Halobacterium salinarum \@ref(fig:3-7a)

Halobacterium salinarum \@ref(fig:6-9c)

Haloferax gibbonsii \@ref(fig:4-10a)

Halohasta litchfieldiae \@ref(fig:4-10b)

Halorubrum litoreum \@ref(fig:4-10)

Methanobacterium formicicum \@ref(fig:2-7d)

Methanoregula formicica \@ref(fig:6-8)

Methanoregula formicica \@ref(fig:3-2b)

Methanospirillum hungatei \@ref(fig:2-8)

Methanospirillum hungatei \@ref(fig:7-3)

Sulfolobus acidocaldarius \@ref(fig:5-11)

Sulfolobus acidocaldarius \@ref(fig:5-12)

Thermococcus kodakaraensis \@ref(fig:6-9)

Thermococcus kodakaraensis \@ref(fig:6-9a)

Thermococcus kodakaraensis \@ref(fig:6-9b)


## Archaellar cone {-}

Thermococcus kodakaraensis \@ref(fig:6-9)

Thermococcus kodakaraensis \@ref(fig:6-9a)

Thermococcus kodakaraensis \@ref(fig:6-9b)

Thermococcus kodakaraensis \@ref(fig:8-3)


## Carboxysomes {-}

Halothiobacillus neapolitanus \@ref(fig:4-7a)

Halothiobacillus neapolitanus \@ref(fig:4-9b)

Hydrogenovibrio crunogenus \@ref(fig:4-7b)

Hydrogenovibrio crunogenus \@ref(fig:4-9a)

Thiomonas intermedia \@ref(fig:4-7)

Thiomonas intermedia \@ref(fig:5-1)


## Cdv belt {-}

Sulfolobus acidocaldarius \@ref(fig:5-11)

Sulfolobus acidocaldarius \@ref(fig:5-12)


## Cell wall (diderm) {-}

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:8-10)

Acetonema longum \@ref(fig:8-10a)

Acetonema longum \@ref(fig:8-11)

Acetonema longum \@ref(fig:8-9)

Agrobacterium tumefaciens \@ref(fig:4-9)

Agrobacterium tumefaciens \@ref(fig:5-8)

Agrobacterium tumefaciens \@ref(fig:9-1)

Amoebophilus asiaticus \@ref(fig:9-7a)

Azospirillum brasilense \@ref(fig:7-4a)

Bacteroidetes JT5 \@ref(fig:10-2)

Bdellovibrio bacteriovorus \@ref(fig:2-10)

Bdellovibrio bacteriovorus \@ref(fig:6-2)

Bdellovibrio bacteriovorus \@ref(fig:6-2a)

Bdellovibrio bacteriovorus \@ref(fig:9-10)

Bdellovibrio bacteriovorus \@ref(fig:9-10a)

Bdellovibrio bacteriovorus \@ref(fig:9-11)

Bdellovibrio bacteriovorus \@ref(fig:9-9)

Borrelia burgdorferi \@ref(fig:2-4a)

Borrelia burgdorferi \@ref(fig:2-4b)

Borrelia burgdorferi \@ref(fig:3-5a)

Borrelia burgdorferi \@ref(fig:6-7)

Brucella abortus \@ref(fig:3-2a)

Campylobacter jejuni \@ref(fig:3-5)

Campylobacter jejuni \@ref(fig:6-4)

Caulobacter crescentus \@ref(fig:2-6)

Caulobacter crescentus \@ref(fig:3-4)

Caulobacter crescentus \@ref(fig:4-1)

Caulobacter crescentus \@ref(fig:5-10)

Caulobacter crescentus \@ref(fig:5-2)

Caulobacter crescentus \@ref(fig:5-7)

Caulobacter crescentus \@ref(fig:5-7a)

Caulobacter crescentus \@ref(fig:10-6)

Caulobacter crescentus \@ref(fig:10-6a)

Caulobacter crescentus \@ref(fig:8-1)

Caulobacter crescentus \@ref(fig:8-4)

Chloroflexi \@ref(fig:4-4)

Chloroflexi \@ref(fig:5-6b)

Cupriavidus necator \@ref(fig:4-8)

Cupriavidus necator \@ref(fig:5-9)

Cupriavidus necator \@ref(fig:5-9a)

Cupriavidus necator \@ref(fig:3-2)

Delftia acidovorans \@ref(fig:2-6a)

Escherichia coli \@ref(fig:2-3a)

Escherichia coli \@ref(fig:10-5)

Escherichia coli \@ref(fig:9-5)

Flavobacterium johnsoniae \@ref(fig:6-11)

Gluconacetobacter hansenii \@ref(fig:9-2)

Halothiobacillus neapolitanus \@ref(fig:4-7a)

Halothiobacillus neapolitanus \@ref(fig:4-9b)

Helicobacter hepaticus \@ref(fig:6-6)

Helicobacter pylori \@ref(fig:6-4a)

Helicobacter pylori \@ref(fig:8-2)

Helicobacter pylori \@ref(fig:9-3a)

Hydrogenovibrio crunogenus \@ref(fig:2-3)

Hydrogenovibrio crunogenus \@ref(fig:4-7b)

Hydrogenovibrio crunogenus \@ref(fig:4-9a)

Hylemonella gracilis \@ref(fig:3-3)

Hylemonella gracilis \@ref(fig:6-3)

Hyphomonas neptunium \@ref(fig:5-3)

Hyphomonas neptunium \@ref(fig:5-3a)

Hyphomonas neptunium \@ref(fig:5-3b)

Idiomarina loihiensis \@ref(fig:5-6)

Legionella pneumophila \@ref(fig:9-3)

Lysobacter antibioticus \@ref(fig:4-8a)

Magnetospirillum magneticum \@ref(fig:7-6)

Methyloprofundus sedimenti \@ref(fig:4-3a)

Mycobacterium marinum \@ref(fig:2-5)

Myxococcus xanthus \@ref(fig:2-4)

Myxococcus xanthus \@ref(fig:2-4c)

Myxococcus xanthus \@ref(fig:6-10)

Myxococcus xanthus \@ref(fig:9-6)

Porphyromonas gingivalis \@ref(fig:9-8)

Prosthecobacter debontii \@ref(fig:2-4d)

Prosthecobacter vanneervenii \@ref(fig:3-6a)

Prosthecobacter vanneervenii \@ref(fig:8-4a)

Proteus mirabilis \@ref(fig:6-5a)

Pseudomonas aeruginosa \@ref(fig:6-3a)

Pseudomonas aeruginosa \@ref(fig:9-4)

Pseudomonas flexibilis \@ref(fig:6-5)

Rhodopseudomonas palustris \@ref(fig:4-3)

Salmonella typhimurium \@ref(fig:7-2)

Shewanella oneidensis \@ref(fig:4-2)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:10-3)

Shewanella oneidensis \@ref(fig:7-1)

Sphingopyxis alaskensis \@ref(fig:5-6a)

Sporomusa acidovorans \@ref(fig:8-10c)

Thiomonas intermedia \@ref(fig:5-1)

Treponema primitia \@ref(fig:6-7a)

Verrucomicrobium spinosum \@ref(fig:3-6)

Vibrio cholerae \@ref(fig:10-4)

Vibrio cholerae \@ref(fig:10-7)

Vibrio cholerae \@ref(fig:7-4)

Vibrio cholerae \@ref(fig:7-5a)

Vibrio cholerae \@ref(fig:9-7)


## Cell wall (monoderm) {-}

Bacillus subtilis \@ref(fig:2-2a)

Bacillus subtilis \@ref(fig:8-5)

Bacillus subtilis \@ref(fig:8-5a)

Bacillus subtilis \@ref(fig:8-6)

Bacillus subtilis \@ref(fig:8-6a)

Bacillus subtilis \@ref(fig:8-6b)

Clostridium thermocellum \@ref(fig:2-7b)

Clostridium thermocellum \@ref(fig:4-5)

Listeria monocytogenes \@ref(fig:2-2)

Methanobacterium formicicum \@ref(fig:2-2c)

Staphylococcus aureus \@ref(fig:5-4)

Tetrasphaera remsis \@ref(fig:5-5)


## Cellulose {-}

Agrobacterium tumefaciens \@ref(fig:9-1)

Gluconacetobacter hansenii \@ref(fig:9-2)


## Chemosensory arrays (membrane-bound) {-}

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:8-9)

Azospirillum brasilense \@ref(fig:7-4a)

Bacillus subtilis \@ref(fig:8-5)

Bdellovibrio bacteriovorus \@ref(fig:2-10)

Bdellovibrio bacteriovorus \@ref(fig:6-2)

Bdellovibrio bacteriovorus \@ref(fig:9-10)

Bdellovibrio bacteriovorus \@ref(fig:9-9)

Campylobacter jejuni \@ref(fig:3-5)

Campylobacter jejuni \@ref(fig:6-4)

Caulobacter crescentus \@ref(fig:10-6)

Caulobacter crescentus \@ref(fig:2-6)

Caulobacter crescentus \@ref(fig:8-4)

Cupriavidus necator \@ref(fig:5-9)

Helicobacter hepaticus \@ref(fig:6-6)

Helicobacter pylori \@ref(fig:6-4a)

Helicobacter pylori \@ref(fig:8-2)

Helicobacter pylori \@ref(fig:9-3a)

Hydrogenovibrio crunogenus \@ref(fig:4-7b)

Hydrogenovibrio crunogenus \@ref(fig:4-9a)

Hylemonella gracilis \@ref(fig:3-3)

Hylemonella gracilis \@ref(fig:6-3)

Magnetospirillum magneticum \@ref(fig:7-6)

Methanoregula formicica \@ref(fig:3-2b)

Methanospirillum hungatei \@ref(fig:2-8)

Methanospirillum hungatei \@ref(fig:7-3)

Proteus mirabilis \@ref(fig:6-5a)

Pseudomonas aeruginosa \@ref(fig:6-3a)

Salmonella typhimurium \@ref(fig:7-2)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:4-2)

Shewanella oneidensis \@ref(fig:7-1)

Thermococcus kodakaraensis \@ref(fig:6-9a)

Thermococcus kodakaraensis \@ref(fig:6-9b)

Treponema primitia \@ref(fig:6-7a)

Vibrio cholerae \@ref(fig:10-4)

Vibrio cholerae \@ref(fig:10-7)

Vibrio cholerae \@ref(fig:7-4)

Vibrio cholerae \@ref(fig:7-5a)

Vibrio cholerae \@ref(fig:9-7)


## Chemosensory arrays (cytoplasmic) {-}

Methanoregula formicica \@ref(fig:3-2b)

Methanoregula formicica \@ref(fig:7-5)

Vibrio cholerae \@ref(fig:7-5a)


## Chlorosomes {-}

Chloroflexi \@ref(fig:4-4)


## CTP synthase filaments {-}

Caulobacter crescentus \@ref(fig:3-4)


## Division plane {-}

Agrobacterium tumefaciens \@ref(fig:5-8)

Caulobacter crescentus \@ref(fig:4-1)

Caulobacter crescentus \@ref(fig:5-10)

Caulobacter crescentus \@ref(fig:5-2)

Caulobacter crescentus \@ref(fig:8-4)

Cupriavidus necator \@ref(fig:3-2)

Cupriavidus necator \@ref(fig:4-8)

Cupriavidus necator \@ref(fig:5-9)

Cupriavidus necator \@ref(fig:5-9a)

Halohasta litchfieldiae \@ref(fig:4-10b)

Listeria monocytogenes \@ref(fig:2-2)

Porphyromonas gingivalis \@ref(fig:9-8)

Sphingopyxis alaskensis \@ref(fig:5-6a)

Staphylococcus aureus \@ref(fig:5-4)

Sulfolobus acidocaldarius \@ref(fig:5-11)

Sulfolobus acidocaldarius \@ref(fig:5-12)

Thiomonas intermedia \@ref(fig:5-1)


## Division septum {-}

Tetrasphaera remsis \@ref(fig:5-5)


## DNA {-}

Haloarcula argentinensis \@ref(fig:2-9)

Hyphomonas neptunium \@ref(fig:5-3)

Vibrio cholerae \@ref(fig:10-7)


## Flagella (external, unsheathed) {-}

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:8-9)

Agrobacterium tumefaciens \@ref(fig:9-1)

Amoebophilus asiaticus \@ref(fig:9-7a)

Azospirillum brasilense \@ref(fig:7-4a)

Bacillus subtilis \@ref(fig:8-6a)

Campylobacter jejuni \@ref(fig:3-5)

Campylobacter jejuni \@ref(fig:6-1)

Campylobacter jejuni \@ref(fig:6-4)

Caulobacter crescentus \@ref(fig:10-6)

Caulobacter crescentus \@ref(fig:5-7)

Caulobacter crescentus \@ref(fig:8-1)

Caulobacter crescentus \@ref(fig:8-4)

Escherichia coli \@ref(fig:9-10a)

Helicobacter pylori \@ref(fig:6-4a)

Hydrogenovibrio crunogenus \@ref(fig:2-3)

Hylemonella gracilis \@ref(fig:3-3)

Hylemonella gracilis \@ref(fig:6-3)

Hyphomonas neptunium \@ref(fig:5-3b)

Listeria monocytogenes \@ref(fig:2-2)

Methylomicrobium alcaliphilum \@ref(fig:2-7a)

Proteus mirabilis \@ref(fig:6-5a)

Pseudomonas flexibilis \@ref(fig:6-5)

Salmonella typhimurium \@ref(fig:7-2)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:10-10)

Shewanella oneidensis \@ref(fig:4-2)

Shewanella oneidensis \@ref(fig:7-1)

Sporomusa acidovorans \@ref(fig:8-10c)


## Flagella (periplasmic) {-}

Borrelia burgdorferi \@ref(fig:2-4a)

Borrelia burgdorferi \@ref(fig:2-4b)

Borrelia burgdorferi \@ref(fig:3-5a)

Borrelia burgdorferi \@ref(fig:6-7)

Treponema primitia \@ref(fig:6-7a)


## Flagella (sheathed) {-}

Bdellovibrio bacteriovorus \@ref(fig:2-10)

Bdellovibrio bacteriovorus \@ref(fig:6-2)

Bdellovibrio bacteriovorus \@ref(fig:9-10)

Helicobacter hepaticus \@ref(fig:6-6)

Vibrio cholerae \@ref(fig:7-4)

Vibrio cholerae \@ref(fig:7-5a)

Vibrio cholerae \@ref(fig:9-11)

Vibrio cholerae \@ref(fig:9-7)


## Flagellar motor (assembling) {-}

Hylemonella gracilis \@ref(fig:6-3)


## Flagellar motor (disassembled) {-}

Caulobacter crescentus \@ref(fig:2-6)

Helicobacter pylori \@ref(fig:8-2)

Hylemonella gracilis \@ref(fig:3-3)

Pseudomonas aeruginosa \@ref(fig:6-3a)

Vibrio cholerae \@ref(fig:7-4)

Vibrio cholerae \@ref(fig:7-5a)

Vibrio cholerae \@ref(fig:9-9)


## Flagellar motors {-}

Bdellovibrio bacteriovorus \@ref(fig:6-2a)

Borrelia burgdorferi \@ref(fig:2-4a)

Borrelia burgdorferi \@ref(fig:3-5a)

Borrelia burgdorferi \@ref(fig:6-7)

Campylobacter jejuni \@ref(fig:6-1)

Campylobacter jejuni \@ref(fig:6-4)

Helicobacter hepaticus \@ref(fig:6-6)

Helicobacter pylori \@ref(fig:6-4a)

Hylemonella gracilis \@ref(fig:6-3)

Proteus mirabilis \@ref(fig:6-5a)

Pseudomonas aeruginosa \@ref(fig:6-3a)

Pseudomonas flexibilis \@ref(fig:6-5)

Shewanella oneidensis \@ref(fig:7-1)

Treponema primitia \@ref(fig:6-7a)

Vibrio cholerae \@ref(fig:7-4)

Vibrio cholerae \@ref(fig:7-5a)

Vibrio cholerae \@ref(fig:9-7)


## FtsZ filaments {-}

Caulobacter crescentus \@ref(fig:5-10)

Cupriavidus necator \@ref(fig:5-9)


## Gas vesicles {-}

Halobacterium salinarum \@ref(fig:3-7a)

Haloquadratum walsbyi \@ref(fig:3-7)


## Gingipains {-}

Porphyromonas gingivalis \@ref(fig:9-8)


## Holdfast {-}

Prosthecobacter vanneervenii \@ref(fig:8-4a)


## Intracytoplasmic membrane {-}

Methylomicrobium alcaliphilum \@ref(fig:2-7a)

Methyloprofundus sedimenti \@ref(fig:4-3a)

Rhodopseudomonas palustris \@ref(fig:4-3)


## Invasion portal {-}

Bdellovibrio bacteriovorus \@ref(fig:9-10)


## MACs {-}

Pseudoalteromonas luteoviolacea \@ref(fig:9-7b)


## Magnetosomes {-}

Magnetospirillum magneticum \@ref(fig:7-6)


## MamK filaments {-}

Magnetospirillum magneticum \@ref(fig:7-6)


## Membrane (inner) {-}

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:8-10)

Acetonema longum \@ref(fig:8-10a)

Acetonema longum \@ref(fig:8-11)

Acetonema longum \@ref(fig:8-9)

Agrobacterium tumefaciens \@ref(fig:4-9)

Agrobacterium tumefaciens \@ref(fig:5-8)

Agrobacterium tumefaciens \@ref(fig:9-1)

Amoebophilus asiaticus \@ref(fig:9-7a)

Azospirillum brasilense \@ref(fig:7-4a)

Bacteroidetes \@ref(fig:10-2)

Bdellovibrio bacteriovorus \@ref(fig:2-10)

Bdellovibrio bacteriovorus \@ref(fig:6-2)

Bdellovibrio bacteriovorus \@ref(fig:6-2a)

Bdellovibrio bacteriovorus \@ref(fig:9-10)

Bdellovibrio bacteriovorus \@ref(fig:9-10a)

Bdellovibrio bacteriovorus \@ref(fig:9-11)

Bdellovibrio bacteriovorus \@ref(fig:9-9)

Borrelia burgdorferi \@ref(fig:2-4a)

Borrelia burgdorferi \@ref(fig:2-4b)

Borrelia burgdorferi \@ref(fig:3-5a)

Borrelia burgdorferi \@ref(fig:6-7)

Brucella abortus \@ref(fig:3-2a)

Campylobacter jejuni \@ref(fig:3-5)

Campylobacter jejuni \@ref(fig:6-4)

Caulobacter crescentus \@ref(fig:10-6)

Caulobacter crescentus \@ref(fig:10-6a)

Caulobacter crescentus \@ref(fig:2-6)

Caulobacter crescentus \@ref(fig:3-4)

Caulobacter crescentus \@ref(fig:4-1)

Caulobacter crescentus \@ref(fig:5-10)

Caulobacter crescentus \@ref(fig:5-2)

Caulobacter crescentus \@ref(fig:5-7)

Caulobacter crescentus \@ref(fig:5-7a)

Caulobacter crescentus \@ref(fig:8-1)

Caulobacter crescentus \@ref(fig:8-4)

Chloroflexi \@ref(fig:4-4)

Chloroflexi \@ref(fig:5-6b)

Cupriavidus necator \@ref(fig:3-2)

Cupriavidus necator \@ref(fig:4-8)

Cupriavidus necator \@ref(fig:5-9)

Cupriavidus necator \@ref(fig:5-9a)

Delftia acidovorans \@ref(fig:2-6a)

Escherichia coli \@ref(fig:10-5)

Escherichia coli \@ref(fig:9-5)

Flavobacterium johnsoniae \@ref(fig:6-11)

Gluconacetobacter hansenii \@ref(fig:9-2)

Halothiobacillus neapolitanus \@ref(fig:4-7a)

Halothiobacillus neapolitanus \@ref(fig:4-9b)

Helicobacter hepaticus \@ref(fig:6-6)

Helicobacter pylori \@ref(fig:6-4a)

Helicobacter pylori \@ref(fig:8-2)

Helicobacter pylori \@ref(fig:9-3a)

Hydrogenovibrio crunogenus \@ref(fig:2-3)

Hydrogenovibrio crunogenus \@ref(fig:4-7b)

Hydrogenovibrio crunogenus \@ref(fig:4-9a)

Hylemonella gracilis \@ref(fig:3-3)

Hylemonella gracilis \@ref(fig:6-3)

Hyphomonas neptunium \@ref(fig:5-3)

Hyphomonas neptunium \@ref(fig:5-3a)

Hyphomonas neptunium \@ref(fig:5-3b)

Idiomarina loihiensis \@ref(fig:5-6)

Legionella pneumophila \@ref(fig:9-3)

Lysobacter antibioticus \@ref(fig:4-8a)

Magnetospirillum magneticum \@ref(fig:7-6)

Methyloprofundus sedimenti \@ref(fig:4-3a)

Mycobacterium marinum \@ref(fig:2-5)

Myxococcus xanthus \@ref(fig:2-4)

Myxococcus xanthus \@ref(fig:2-4c)

Myxococcus xanthus \@ref(fig:6-10)

Myxococcus xanthus \@ref(fig:9-6)

Porphyromonas gingivalis \@ref(fig:9-8)

Prosthecobacter debontii \@ref(fig:2-4d)

Prosthecobacter vanneervenii \@ref(fig:3-6a)

Prosthecobacter vanneervenii \@ref(fig:8-4a)

Proteus mirabilis \@ref(fig:6-5a)

Pseudomonas aeruginosa \@ref(fig:6-3a)

Pseudomonas aeruginosa \@ref(fig:9-4)

Pseudomonas flexibilis \@ref(fig:6-5)

Rhodopseudomonas palustris \@ref(fig:4-3)

Salmonella typhimurium \@ref(fig:7-2)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:10-3)

Shewanella oneidensis \@ref(fig:4-2)

Shewanella oneidensis \@ref(fig:7-1)

Simkania negevensis \@ref(fig:3-1)

Sphingopyxis alaskensis \@ref(fig:5-6a)

Sporomusa acidovorans \@ref(fig:8-10c)

Thiomonas intermedia \@ref(fig:5-1)

Treponema primitia \@ref(fig:6-7a)

Verrucomicrobium spinosum \@ref(fig:3-6)

Vibrio cholerae \@ref(fig:10-4)

Vibrio cholerae \@ref(fig:10-7)

Vibrio cholerae \@ref(fig:7-4)

Vibrio cholerae \@ref(fig:7-5a)

Vibrio cholerae \@ref(fig:9-7)


## Membrane (monoderm) {-}

Bacillus subtilis \@ref(fig:8-5)

Bacillus subtilis \@ref(fig:8-5a)

Bacillus subtilis \@ref(fig:8-6)

Bacillus subtilis \@ref(fig:8-6a)

Bacillus subtilis \@ref(fig:8-6b)

Clostridium thermocellum \@ref(fig:2-7b)

Clostridium thermocellum \@ref(fig:4-5)

Haloarcula argentinensis \@ref(fig:2-9)

Halobacterium salinarum \@ref(fig:3-7a)

Halobacterium salinarum \@ref(fig:6-9c)

Haloferax gibbonsii \@ref(fig:4-10a)

Halohasta litchfieldiae \@ref(fig:4-10b)

Halomicrobium mukohataei \@ref(fig:2-4e)

Haloquadratum walsbyi \@ref(fig:3-7)

Halorubrum litoreum \@ref(fig:4-10)

Listeria monocytogenes \@ref(fig:2-2)

Methanobacterium formicicum \@ref(fig:2-2c)

Methanoregula formicica \@ref(fig:2-7d)

Methanoregula formicica \@ref(fig:3-2b)

Methanoregula formicica \@ref(fig:6-8)

Methanoregula formicica \@ref(fig:7-5)

Methanospirillum hungatei \@ref(fig:2-8)

Methanospirillum hungatei \@ref(fig:7-3)

Methylomicrobium alcaliphilum \@ref(fig:2-7a)

Mycoplasma genitalium \@ref(fig:2-1)

Mycoplasma pneumoniae \@ref(fig:6-12)

Nitrosopumilus maritimus \@ref(fig:2-7c)

Staphylococcus aureus \@ref(fig:5-4)

Sulfolobus acidocaldarius \@ref(fig:5-11)

Sulfolobus acidocaldarius \@ref(fig:5-12)

Sulfolobus solfataricus \@ref(fig:10-8)

Sulfolobus solfataricus \@ref(fig:10-9)

Sulfolobus solfataricus \@ref(fig:2-7)

Tetrasphaera remsis \@ref(fig:5-5)

Thermococcus kodakaraensis \@ref(fig:6-9)

Thermococcus kodakaraensis \@ref(fig:6-9a)

Thermococcus kodakaraensis \@ref(fig:6-9b)

Thermococcus kodakaraensis \@ref(fig:8-3)


## Membrane (outer) {-}

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:8-10)

Acetonema longum \@ref(fig:8-10a)

Acetonema longum \@ref(fig:8-11)

Acetonema longum \@ref(fig:8-9)

Agrobacterium tumefaciens \@ref(fig:4-9)

Agrobacterium tumefaciens \@ref(fig:5-8)

Agrobacterium tumefaciens \@ref(fig:9-1)

Amoebophilus asiaticus \@ref(fig:9-7a)

Azospirillum brasilense \@ref(fig:7-4a)

Bacteroidetes \@ref(fig:10-2)

Bdellovibrio bacteriovorus \@ref(fig:2-10)

Bdellovibrio bacteriovorus \@ref(fig:6-2)

Bdellovibrio bacteriovorus \@ref(fig:6-2a)

Bdellovibrio bacteriovorus \@ref(fig:9-10)

Bdellovibrio bacteriovorus \@ref(fig:9-10a)

Bdellovibrio bacteriovorus \@ref(fig:9-11)

Bdellovibrio bacteriovorus \@ref(fig:9-9)

Borrelia burgdorferi \@ref(fig:2-4a)

Borrelia burgdorferi \@ref(fig:2-4b)

Borrelia burgdorferi \@ref(fig:3-5a)

Borrelia burgdorferi \@ref(fig:6-7)

Brucella abortus \@ref(fig:3-2a)

Campylobacter jejuni \@ref(fig:3-5)

Campylobacter jejuni \@ref(fig:6-1)

Campylobacter jejuni \@ref(fig:6-4)

Caulobacter crescentus \@ref(fig:10-6)

Caulobacter crescentus \@ref(fig:10-6a)

Caulobacter crescentus \@ref(fig:2-6)

Caulobacter crescentus \@ref(fig:3-4)

Caulobacter crescentus \@ref(fig:4-1)

Caulobacter crescentus \@ref(fig:5-10)

Caulobacter crescentus \@ref(fig:5-2)

Caulobacter crescentus \@ref(fig:5-7)

Caulobacter crescentus \@ref(fig:5-7a)

Caulobacter crescentus \@ref(fig:8-1)

Caulobacter crescentus \@ref(fig:8-4)

Chloroflexi \@ref(fig:4-4)

Chloroflexi \@ref(fig:5-6b)

Cupriavidus necator \@ref(fig:3-2)

Cupriavidus necator \@ref(fig:4-8)

Cupriavidus necator \@ref(fig:5-9)

Cupriavidus necator \@ref(fig:5-9a)

Delftia acidovorans \@ref(fig:2-6a)

Escherichia coli \@ref(fig:10-5)

Escherichia coli \@ref(fig:9-5)

Flavobacterium johnsoniae \@ref(fig:6-11)

Gluconacetobacter hansenii \@ref(fig:9-2)

Halothiobacillus neapolitanus \@ref(fig:4-7a)

Halothiobacillus neapolitanus \@ref(fig:4-9b)

Helicobacter hepaticus \@ref(fig:6-6)

Helicobacter pylori \@ref(fig:6-4a)

Helicobacter pylori \@ref(fig:8-2)

Helicobacter pylori \@ref(fig:9-3a)

Hydrogenovibrio crunogenus \@ref(fig:2-3)

Hydrogenovibrio crunogenus \@ref(fig:4-7b)

Hydrogenovibrio crunogenus \@ref(fig:4-9a)

Hylemonella gracilis \@ref(fig:3-3)

Hylemonella gracilis \@ref(fig:6-3)

Hyphomonas neptunium \@ref(fig:5-3)

Hyphomonas neptunium \@ref(fig:5-3a)

Hyphomonas neptunium \@ref(fig:5-3b)

Idiomarina loihiensis \@ref(fig:5-6)

Legionella pneumophila \@ref(fig:9-3)

Lysobacter antibioticus \@ref(fig:4-8a)

Magnetospirillum magneticum \@ref(fig:7-6)

Methyloprofundus sedimenti \@ref(fig:4-3a)

Mycobacterium marinum \@ref(fig:2-5)

Myxococcus xanthus \@ref(fig:2-4)

Myxococcus xanthus \@ref(fig:2-4c)

Myxococcus xanthus \@ref(fig:6-10)

Myxococcus xanthus \@ref(fig:9-6)

Porphyromonas gingivalis \@ref(fig:9-8)

Prosthecobacter debontii \@ref(fig:2-4d)

Prosthecobacter vanneervenii \@ref(fig:3-6a)

Prosthecobacter vanneervenii \@ref(fig:8-4a)

Proteus mirabilis \@ref(fig:6-5a)

Pseudomonas aeruginosa \@ref(fig:6-3a)

Pseudomonas aeruginosa \@ref(fig:9-4)

Pseudomonas flexibilis \@ref(fig:6-5)

Rhodopseudomonas palustris \@ref(fig:4-3)

Salmonella typhimurium \@ref(fig:7-2)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:10-3)

Shewanella oneidensis \@ref(fig:4-2)

Shewanella oneidensis \@ref(fig:7-1)

Simkania negevensis \@ref(fig:3-1)

Sphingopyxis alaskensis \@ref(fig:5-6a)

Sporomusa acidovorans \@ref(fig:8-10c)

Thiomonas intermedia \@ref(fig:5-1)

Treponema primitia \@ref(fig:6-7a)

Verrucomicrobium spinosum \@ref(fig:3-6)

Vibrio cholerae \@ref(fig:10-4)

Vibrio cholerae \@ref(fig:10-7)

Vibrio cholerae \@ref(fig:7-4)

Vibrio cholerae \@ref(fig:7-5a)

Vibrio cholerae \@ref(fig:9-7)


## Cellulose {-}

Agrobacterium tumefaciens \@ref(fig:9-1)

Gluconacetobacter hansenii \@ref(fig:9-2)


## Metal deposits {-}

Shewanella oneidensis \@ref(fig:4-2)


## Microtubules {-}

Prosthecobacter debontii \@ref(fig:2-4d)

Prosthecobacter vanneervenii \@ref(fig:3-6a)

Prosthecobacter vanneervenii \@ref(fig:8-4a)


## Nanopods {-}

Delftia acidovorans \@ref(fig:2-6a)


## Nanowires {-}

Shewanella oneidensis \@ref(fig:4-2)


## Nucleoid {-}

Bdellovibrio bacteriovorus \@ref(fig:2-10)

Bdellovibrio bacteriovorus \@ref(fig:6-2)

Bdellovibrio bacteriovorus \@ref(fig:9-10)

Bdellovibrio bacteriovorus \@ref(fig:9-10a)

Bdellovibrio bacteriovorus \@ref(fig:9-11)

Bdellovibrio bacteriovorus \@ref(fig:9-9)

Caulobacter crescentus \@ref(fig:8-1)

Vibrio cholerae \@ref(fig:10-7)


## Pdu microcompartments {-}

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:8-9)


## Phage capsids {-}

Bacteroidetes \@ref(fig:10-2)

Caulobacter crescentus \@ref(fig:10-6)

Caulobacter crescentus \@ref(fig:10-6a)

Escherichia coli \@ref(fig:10-5)

Pseudomonas aeruginosa \@ref(fig:9-4)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:10-10)

Shewanella oneidensis \@ref(fig:10-3)

Sulfolobus solfataricus \@ref(fig:10-8)

Vibrio cholerae \@ref(fig:10-4)

Vibrio cholerae \@ref(fig:10-7)


## Phage head fibers {-}

Caulobacter crescentus \@ref(fig:10-6)


## Phage tail fibers {-}

Bacteroidetes \@ref(fig:10-2)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:10-10)

Shewanella oneidensis \@ref(fig:10-3)

Vibrio cholerae \@ref(fig:10-4)


## Phage tails {-}

Bacteroidetes \@ref(fig:10-2)

Caulobacter crescentus \@ref(fig:10-6)

Caulobacter crescentus \@ref(fig:10-6a)

Pseudomonas aeruginosa \@ref(fig:9-4)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:10-10)

Shewanella oneidensis \@ref(fig:10-3)

Vibrio cholerae \@ref(fig:10-7)


## Pili {-}

Amoebophilus asiaticus \@ref(fig:9-7a)

Bacteroidetes \@ref(fig:10-2)

Bdellovibrio bacteriovorus \@ref(fig:6-2)

Caulobacter crescentus \@ref(fig:10-6a)

Caulobacter crescentus \@ref(fig:2-6)

Caulobacter crescentus \@ref(fig:8-1)

Clostridium thermocellum \@ref(fig:2-7b)

Cupriavidus necator \@ref(fig:5-9)

Escherichia coli \@ref(fig:10-5)

Escherichia coli \@ref(fig:9-10)

Escherichia coli \@ref(fig:9-10a)

Halothiobacillus neapolitanus \@ref(fig:4-7a)

Hydrogenovibrio crunogenus \@ref(fig:2-3)

Methanoregula formicica \@ref(fig:6-8)

Methanospirillum hungatei \@ref(fig:2-8)

Methanospirillum hungatei \@ref(fig:7-3)

Prosthecobacter debontii \@ref(fig:2-4d)

Prosthecobacter vanneervenii \@ref(fig:8-4a)

Pseudomonas flexibilis \@ref(fig:6-5)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:7-1)

Sulfolobus solfataricus \@ref(fig:10-8)

Sulfolobus solfataricus \@ref(fig:10-9)

Sulfolobus solfataricus \@ref(fig:2-7)

Thiomonas intermedia \@ref(fig:4-7)

Thiomonas intermedia \@ref(fig:5-1)

Treponema primitia \@ref(fig:6-7a)

Verrucomicrobium spinosum \@ref(fig:3-6)

Vibrio cholerae \@ref(fig:10-7)

Vibrio cholerae \@ref(fig:9-7)


## Pili (Type IV) {-}

Bdellovibrio bacteriovorus \@ref(fig:2-10)

Bdellovibrio bacteriovorus \@ref(fig:9-9)

Myxococcus xanthus \@ref(fig:2-4)

Myxococcus xanthus \@ref(fig:6-10)

Myxococcus xanthus \@ref(fig:9-6)


## PopZ {-}

Caulobacter crescentus \@ref(fig:5-2)

Caulobacter crescentus \@ref(fig:5-7)


## RecA/RadA filaments {-}

Helicobacter pylori \@ref(fig:8-2)

Thermococcus kodakaraensis \@ref(fig:8-3)


## Ribosomes {-}

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:8-11)

Acetonema longum \@ref(fig:8-9)

Agrobacterium tumefaciens \@ref(fig:4-9)

Agrobacterium tumefaciens \@ref(fig:5-8)

Agrobacterium tumefaciens \@ref(fig:9-1)

Amoebophilus asiaticus \@ref(fig:9-7a)

Azospirillum brasilense \@ref(fig:7-4a)

Bacillus subtilis \@ref(fig:8-6a)

Bacillus subtilis \@ref(fig:8-7)

Bacteroidetes \@ref(fig:10-2)

Bdellovibrio bacteriovorus \@ref(fig:2-10)

Bdellovibrio bacteriovorus \@ref(fig:6-2)

Bdellovibrio bacteriovorus \@ref(fig:9-10)

Bdellovibrio bacteriovorus \@ref(fig:9-10a)

Bdellovibrio bacteriovorus \@ref(fig:9-11)

Bdellovibrio bacteriovorus \@ref(fig:9-9)

Borrelia burgdorferi \@ref(fig:2-4a)

Borrelia burgdorferi \@ref(fig:2-4b)

Borrelia burgdorferi \@ref(fig:3-5a)

Borrelia burgdorferi \@ref(fig:6-7)

Campylobacter jejuni \@ref(fig:3-5)

Campylobacter jejuni \@ref(fig:6-4)

Caulobacter crescentus \@ref(fig:10-6)

Caulobacter crescentus \@ref(fig:10-6a)

Caulobacter crescentus \@ref(fig:2-6)

Caulobacter crescentus \@ref(fig:3-4)

Caulobacter crescentus \@ref(fig:4-1)

Caulobacter crescentus \@ref(fig:5-10)

Caulobacter crescentus \@ref(fig:5-2)

Caulobacter crescentus \@ref(fig:5-7)

Caulobacter crescentus \@ref(fig:5-7a)

Caulobacter crescentus \@ref(fig:8-1)

Caulobacter crescentus \@ref(fig:8-4)

Chloroflexi \@ref(fig:4-4)

Chloroflexi \@ref(fig:5-6b)

Clostridium thermocellum \@ref(fig:2-7b)

Clostridium thermocellum \@ref(fig:4-5)

Cupriavidus necator \@ref(fig:3-2)

Cupriavidus necator \@ref(fig:4-8)

Cupriavidus necator \@ref(fig:5-9)

Escherichia coli \@ref(fig:10-5)

Escherichia coli \@ref(fig:9-5)

Flavobacterium johnsoniae \@ref(fig:6-11)

Gluconacetobacter hansenii \@ref(fig:9-2)

Halobacterium salinarum \@ref(fig:3-7a)

Halobacterium salinarum \@ref(fig:6-9c)

Haloferax gibbonsii \@ref(fig:4-10a)

Halohasta litchfieldiae \@ref(fig:4-10b)

Halomicrobium mukohataei \@ref(fig:2-4e)

Haloquadratum walsbyi \@ref(fig:3-7)

Halorubrum litoreum \@ref(fig:4-10)

Halothiobacillus neapolitanus \@ref(fig:4-7a)

Halothiobacillus neapolitanus \@ref(fig:4-9b)

Helicobacter hepaticus \@ref(fig:6-6)

Helicobacter pylori \@ref(fig:6-4a)

Helicobacter pylori \@ref(fig:8-2)

Helicobacter pylori \@ref(fig:9-3a)

Hydrogenovibrio crunogenus \@ref(fig:2-3)

Hydrogenovibrio crunogenus \@ref(fig:4-7b)

Hydrogenovibrio crunogenus \@ref(fig:4-9a)

Hylemonella gracilis \@ref(fig:3-3)

Hylemonella gracilis \@ref(fig:6-3)

Hyphomonas neptunium \@ref(fig:5-3)

Hyphomonas neptunium \@ref(fig:5-3a)

Hyphomonas neptunium \@ref(fig:5-3b)

Idiomarina loihiensis \@ref(fig:5-6)

Legionella pneumophila \@ref(fig:9-3)

Listeria monocytogenes \@ref(fig:2-2)

Lysobacter antibioticus \@ref(fig:4-8a)

Magnetospirillum magneticum \@ref(fig:7-6)

Methanobacterium formicicum \@ref(fig:2-2c)

Methanoregula formicica \@ref(fig:2-7d)

Methanoregula formicica \@ref(fig:3-2b)

Methanospirillum hungatei \@ref(fig:2-8)

Methanospirillum hungatei \@ref(fig:7-3)

Methyloprofundus sedimenti \@ref(fig:4-3a)

Mycobacterium marinum \@ref(fig:2-5)

Mycoplasma genitalium \@ref(fig:2-1)

Mycoplasma pneumoniae \@ref(fig:6-12)

Myxococcus xanthus \@ref(fig:2-4c)

Myxococcus xanthus \@ref(fig:6-10)

Myxococcus xanthus \@ref(fig:9-6)

Nitrosopumilus maritimus \@ref(fig:2-7c)

Porphyromonas gingivalis \@ref(fig:9-8)

Prosthecobacter debontii \@ref(fig:2-4d)

Prosthecobacter vanneervenii \@ref(fig:3-6a)

Prosthecobacter vanneervenii \@ref(fig:8-4a)

Proteus mirabilis \@ref(fig:6-5a)

Pseudomonas aeruginosa \@ref(fig:6-3a)

Pseudomonas aeruginosa \@ref(fig:9-4)

Pseudomonas flexibilis \@ref(fig:6-5)

Salmonella typhimurium \@ref(fig:7-2)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:10-3)

Shewanella oneidensis \@ref(fig:4-2)

Shewanella oneidensis \@ref(fig:7-1)

Simkania negevensis \@ref(fig:3-1)

Sphingopyxis alaskensis \@ref(fig:5-6a)

Sporomusa acidovorans \@ref(fig:8-10c)

Staphylococcus aureus \@ref(fig:5-4)

Sulfolobus acidocaldarius \@ref(fig:5-11)

Sulfolobus acidocaldarius \@ref(fig:5-12)

Tetrasphaera remsis \@ref(fig:5-5)

Thermococcus kodakaraensis \@ref(fig:6-9)

Thermococcus kodakaraensis \@ref(fig:6-9a)

Thermococcus kodakaraensis \@ref(fig:6-9b)

Thermococcus kodakaraensis \@ref(fig:8-3)

Thiomonas intermedia \@ref(fig:4-7)

Thiomonas intermedia \@ref(fig:5-1)

Treponema primitia \@ref(fig:6-7a)

Vibrio cholerae \@ref(fig:10-4)

Vibrio cholerae \@ref(fig:10-7)

Vibrio cholerae \@ref(fig:7-4)

Vibrio cholerae \@ref(fig:7-5a)

Vibrio cholerae \@ref(fig:9-7)


## Sheath {-}

Methanospirillum hungatei \@ref(fig:2-8)

Methanospirillum hungatei \@ref(fig:7-3)


## Spore coat {-}

Acetonema longum \@ref(fig:8-10b)

Acetonema longum \@ref(fig:8-11)

Bacillus subtilis \@ref(fig:8-7)

Bacillus subtilis \@ref(fig:8-8)


## Spore cortex {-}

Acetonema longum \@ref(fig:8-10)

Acetonema longum \@ref(fig:8-10a)

Acetonema longum \@ref(fig:8-10b)

Bacillus subtilis \@ref(fig:8-6b)

Bacillus subtilis \@ref(fig:8-7)

Bacillus subtilis \@ref(fig:8-8)


## Spore membrane (inner) {-}

Acetonema longum \@ref(fig:8-10)

Acetonema longum \@ref(fig:8-10a)

Acetonema longum \@ref(fig:8-10b)

Bacillus subtilis \@ref(fig:8-6b)

Bacillus subtilis \@ref(fig:8-7)

Bacillus subtilis \@ref(fig:8-8)


## Spore membrane (outer) {-}

Acetonema longum \@ref(fig:8-10)

Acetonema longum \@ref(fig:8-10a)

Acetonema longum \@ref(fig:8-10b)

Bacillus subtilis \@ref(fig:8-6b)

Bacillus subtilis \@ref(fig:8-7)

Bacillus subtilis \@ref(fig:8-8)


## Sporulation plane {-}

Bacillus subtilis \@ref(fig:8-5a)


## Sporulation septum {-}

Acetonema longum \@ref(fig:8-9)

Bacillus subtilis \@ref(fig:8-5)

Bacillus subtilis \@ref(fig:8-6)

Bacillus subtilis \@ref(fig:8-6a)


## Stalk bands {-}

Caulobacter crescentus \@ref(fig:4-1)


## Storage granules {-}

Acetonema longum \@ref(fig:8-10)

Acetonema longum \@ref(fig:8-10a)

Acetonema longum \@ref(fig:8-10b)

Acetonema longum \@ref(fig:8-11)

Acetonema longum \@ref(fig:8-9)

Agrobacterium tumefaciens \@ref(fig:4-9)

Agrobacterium tumefaciens \@ref(fig:5-8)

Agrobacterium tumefaciens \@ref(fig:9-1)

Azospirillum brasilense \@ref(fig:7-4a)

Bacteroidetes \@ref(fig:10-2)

Bdellovibrio bacteriovorus \@ref(fig:6-2)

Bdellovibrio bacteriovorus \@ref(fig:9-10)

Bdellovibrio bacteriovorus \@ref(fig:9-10a)

Bdellovibrio bacteriovorus \@ref(fig:9-11)

Bdellovibrio bacteriovorus \@ref(fig:9-9)

Brucella abortus \@ref(fig:3-2a)

Campylobacter jejuni \@ref(fig:3-5)

Campylobacter jejuni \@ref(fig:6-4)

Caulobacter crescentus \@ref(fig:2-6)

Caulobacter crescentus \@ref(fig:3-4)

Caulobacter crescentus \@ref(fig:4-1)

Caulobacter crescentus \@ref(fig:5-10)

Caulobacter crescentus \@ref(fig:5-2)

Caulobacter crescentus \@ref(fig:5-7)

Caulobacter crescentus \@ref(fig:5-7a)

Caulobacter crescentus \@ref(fig:8-1)

Caulobacter crescentus \@ref(fig:8-4)

Cupriavidus necator \@ref(fig:3-2)

Cupriavidus necator \@ref(fig:4-8)

Cupriavidus necator \@ref(fig:5-9)

Cupriavidus necator \@ref(fig:5-9a)

Escherichia coli \@ref(fig:9-5)

Flavobacterium johnsoniae \@ref(fig:6-11)

Gluconacetobacter hansenii \@ref(fig:9-2)

Haloarcula argentinensis \@ref(fig:2-9)

Haloferax gibbonsii \@ref(fig:4-10a)

Halohasta litchfieldiae \@ref(fig:4-10b)

Haloquadratum walsbyi \@ref(fig:3-7)

Halorubrum litoreum \@ref(fig:4-10)

Halothiobacillus neapolitanus \@ref(fig:4-7a)

Halothiobacillus neapolitanus \@ref(fig:4-9b)

Helicobacter hepaticus \@ref(fig:6-6)

Helicobacter pylori \@ref(fig:6-4a)

Helicobacter pylori \@ref(fig:8-2)

Hydrogenovibrio crunogenus \@ref(fig:2-3)

Hydrogenovibrio crunogenus \@ref(fig:4-7b)

Hydrogenovibrio crunogenus \@ref(fig:4-9a)

Hyphomonas neptunium \@ref(fig:5-3a)

Legionella pneumophila \@ref(fig:9-3)

Lysobacter antibioticus \@ref(fig:4-8a)

Magnetospirillum magneticum \@ref(fig:7-6)

Methanospirillum hungatei \@ref(fig:2-8)

Methanospirillum hungatei \@ref(fig:7-3)

Methylomicrobium alcaliphilum \@ref(fig:2-7a)

Methyloprofundus sedimenti \@ref(fig:4-3a)

Mycobacterium marinum \@ref(fig:2-5)

Myxococcus xanthus \@ref(fig:2-4c)

Myxococcus xanthus \@ref(fig:6-10)

Myxococcus xanthus \@ref(fig:9-6)

Prosthecobacter debontii \@ref(fig:2-4d)

Prosthecobacter vanneervenii \@ref(fig:3-6a)

Prosthecobacter vanneervenii \@ref(fig:8-4a)

Pseudomonas aeruginosa \@ref(fig:6-3a)

Pseudomonas aeruginosa \@ref(fig:9-4)

Pseudomonas flexibilis \@ref(fig:6-5)

Rhodopseudomonas palustris \@ref(fig:4-3)

Sphingopyxis alaskensis \@ref(fig:5-6a)

Sulfolobus acidocaldarius \@ref(fig:5-11)

Sulfolobus acidocaldarius \@ref(fig:5-12)

Sulfolobus solfataricus \@ref(fig:10-8)

Sulfolobus solfataricus \@ref(fig:2-7)

Tetrasphaera remsis \@ref(fig:5-5)

Thiomonas intermedia \@ref(fig:4-7)

Thiomonas intermedia \@ref(fig:5-1)

Verrucomicrobium spinosum \@ref(fig:3-6)

Vibrio cholerae \@ref(fig:10-4)

Vibrio cholerae \@ref(fig:9-7)


## Surface layer {-}

Caulobacter crescentus \@ref(fig:10-6)

Caulobacter crescentus \@ref(fig:10-6a)

Caulobacter crescentus \@ref(fig:2-6)

Caulobacter crescentus \@ref(fig:3-4)

Caulobacter crescentus \@ref(fig:4-1)

Caulobacter crescentus \@ref(fig:5-10)

Caulobacter crescentus \@ref(fig:5-2)

Caulobacter crescentus \@ref(fig:5-7)

Caulobacter crescentus \@ref(fig:5-7a)

Caulobacter crescentus \@ref(fig:8-4)

Clostridium thermocellum \@ref(fig:2-7b)

Clostridium thermocellum \@ref(fig:4-5)

Delftia acidovorans \@ref(fig:2-6a)

Haloarcula argentinensis \@ref(fig:2-9)

Halobacterium salinarum \@ref(fig:3-7a)

Halobacterium salinarum \@ref(fig:6-9c)

Haloferax gibbonsii \@ref(fig:4-10a)

Halohasta litchfieldiae \@ref(fig:4-10b)

Halomicrobium mukohataei \@ref(fig:2-4e)

Haloquadratum walsbyi \@ref(fig:3-7)

Halorubrum litoreum \@ref(fig:4-10)

Methanoregula formicica \@ref(fig:2-7d)

Methanoregula formicica \@ref(fig:3-2b)

Methanoregula formicica \@ref(fig:6-8)

Methanoregula formicica \@ref(fig:7-5)

Methanospirillum hungatei \@ref(fig:2-8)

Methanospirillum hungatei \@ref(fig:7-3)

Methylomicrobium alcaliphilum \@ref(fig:2-7a)

Methyloprofundus sedimenti \@ref(fig:4-3a)

Nitrosopumilus maritimus \@ref(fig:2-7c)

Sulfolobus acidocaldarius \@ref(fig:5-11)

Sulfolobus acidocaldarius \@ref(fig:5-12)

Sulfolobus solfataricus \@ref(fig:10-8)

Sulfolobus solfataricus \@ref(fig:10-9)

Sulfolobus solfataricus \@ref(fig:2-7)

Thermococcus kodakaraensis \@ref(fig:6-9)

Thermococcus kodakaraensis \@ref(fig:6-9a)

Thermococcus kodakaraensis \@ref(fig:6-9b)

Thermococcus kodakaraensis \@ref(fig:8-3)

Thiomonas intermedia \@ref(fig:4-7)

Thiomonas intermedia \@ref(fig:5-1)


## Terminal organelles {-}

Mycoplasma genitalium \@ref(fig:2-1)

Mycoplasma pneumoniae \@ref(fig:6-12)


## Type II secretion systems {-}

Legionella pneumophila \@ref(fig:9-3)

Shewanella oneidensis \@ref(fig:10-1)

Vibrio cholerae \@ref(fig:10-4)


## Type III secretion systems {-}

Pseudomonas aeruginosa \@ref(fig:9-4)


## Type IV secretion systems {-}

Helicobacter pylori \@ref(fig:9-3a)

Legionella pneumophila \@ref(fig:9-3)


## Type V secretion systems {-}

Escherichia coli \@ref(fig:9-5)


## Type VI secretion systems {-}

Agrobacterium tumefaciens \@ref(fig:9-1)

Azospirillum brasilense \@ref(fig:9-7a)

Myxococcus xanthus \@ref(fig:9-6)

Proteus mirabilis \@ref(fig:6-5a)

Vibrio cholerae \@ref(fig:9-7)


## Type IX secretion systems {-}

Porphyromonas gingivalis \@ref(fig:9-8)


## Unipolar polysaccharide {-}

Agrobacterium tumefaciens \@ref(fig:9-1)


## Unknown structures {-}

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:8-9)

Agrobacterium tumefaciens \@ref(fig:9-1)

Amoebophilus asiaticus \@ref(fig:9-7a)

Bacillus subtilis \@ref(fig:8-6a)

Bacillus subtilis \@ref(fig:8-6b)

Bdellovibrio bacteriovorus \@ref(fig:2-10)

Bdellovibrio bacteriovorus \@ref(fig:6-2)

Borrelia burgdorferi \@ref(fig:3-5a)

Campylobacter jejuni \@ref(fig:3-5)

Campylobacter jejuni \@ref(fig:6-4)

Caulobacter crescentus \@ref(fig:8-4)

Chloroflexi \@ref(fig:4-4)

Chloroflexi \@ref(fig:5-6b)

Cupriavidus necator \@ref(fig:5-9)

Flavobacterium johnsoniae \@ref(fig:6-11)

Haloarcula argentinensis \@ref(fig:2-9)

Halohasta litchfieldiae \@ref(fig:4-10b)

Haloquadratum walsbyi \@ref(fig:3-7)

Halorubrum litoreum \@ref(fig:4-10)

Halothiobacillus neapolitanus \@ref(fig:4-9b)

Helicobacter pylori \@ref(fig:6-4a)

Helicobacter pylori \@ref(fig:9-3a)

Hydrogenovibrio crunogenus \@ref(fig:4-7b)

Hydrogenovibrio crunogenus \@ref(fig:4-9a)

Listeria monocytogenes \@ref(fig:2-2)

Methanoregula formicica \@ref(fig:2-7d)

Methanoregula formicica \@ref(fig:3-2b)

Methanoregula formicica \@ref(fig:6-8)

Methanoregula formicica \@ref(fig:7-5)

Methylomicrobium alcaliphilum \@ref(fig:2-7a)

Mycobacterium marinum \@ref(fig:2-5)

Myxococcus xanthus \@ref(fig:2-4)

Myxococcus xanthus \@ref(fig:9-6)

Nitrosopumilus maritimus \@ref(fig:2-7c)

Prosthecobacter debontii \@ref(fig:2-4d)

Pseudoalteromonas luteoviolacea \@ref(fig:9-7b)

Sporomusa acidovorans \@ref(fig:8-10c)

Sulfolobus acidocaldarius \@ref(fig:5-12)

Thermococcus kodakaraensis \@ref(fig:6-9)

Thermococcus kodakaraensis \@ref(fig:6-9a)

Thermococcus kodakaraensis \@ref(fig:6-9b)

Treponema primitia \@ref(fig:6-7a)

Vibrio cholerae \@ref(fig:10-4)

Vibrio cholerae \@ref(fig:10-7)

Vibrio cholerae \@ref(fig:9-7)


## Vesicles (cytoplasmic) {-}

Acetonema longum \@ref(fig:8-9)

Agrobacterium tumefaciens \@ref(fig:4-9)

Amoebophilus asiaticus \@ref(fig:9-7a)

Azospirillum brasilense \@ref(fig:7-4a)

Bdellovibrio bacteriovorus \@ref(fig:9-10)

Bdellovibrio bacteriovorus \@ref(fig:9-10a)

Bdellovibrio bacteriovorus \@ref(fig:9-11)

Brucella abortus \@ref(fig:3-2a)

Caulobacter crescentus \@ref(fig:10-6a)

Caulobacter crescentus \@ref(fig:3-4)

Caulobacter crescentus \@ref(fig:5-2)

Caulobacter crescentus \@ref(fig:5-7a)

Caulobacter crescentus \@ref(fig:8-1)

Escherichia coli \@ref(fig:10-5)

Escherichia coli \@ref(fig:9-5)

Gluconacetobacter hansenii \@ref(fig:9-2)

Halobacterium salinarum \@ref(fig:6-9c)

Halomicrobium mukohataei \@ref(fig:2-4e)

Helicobacter pylori \@ref(fig:6-4a)

Helicobacter pylori \@ref(fig:8-2)

Legionella pneumophila \@ref(fig:9-3)

Listeria monocytogenes \@ref(fig:2-2)

Methanospirillum hungatei \@ref(fig:2-8)

Methanospirillum hungatei \@ref(fig:7-3)

Myxococcus xanthus \@ref(fig:2-4c)

Prosthecobacter debontii \@ref(fig:2-4d)

Prosthecobacter vanneervenii \@ref(fig:3-6a)

Proteus mirabilis \@ref(fig:6-5a)

Pseudomonas aeruginosa \@ref(fig:6-3a)

Pseudomonas flexibilis \@ref(fig:6-5)

Shewanella oneidensis \@ref(fig:10-1)

Shewanella oneidensis \@ref(fig:10-3)

Shewanella oneidensis \@ref(fig:4-2)

Simkania negevensis \@ref(fig:3-1)

Sporomusa acidovorans \@ref(fig:8-10c)

Treponema primitia \@ref(fig:6-7a)

Vibrio cholerae \@ref(fig:9-7)


## Vesicles (extracellular) {-}

Acetonema longum \@ref(fig:4-6)

Acetonema longum \@ref(fig:8-11)

Agrobacterium tumefaciens \@ref(fig:9-1)

Bdellovibrio bacteriovorus \@ref(fig:9-11)

Borrelia burgdorferi \@ref(fig:2-4a)

Borrelia burgdorferi \@ref(fig:2-4b)

Cupriavidus necator \@ref(fig:3-2)

Haloferax gibbonsii \@ref(fig:4-10a)

Halomicrobium mukohataei \@ref(fig:2-4e)

Haloquadratum walsbyi \@ref(fig:3-7)

Helicobacter pylori \@ref(fig:8-2)

Hylemonella gracilis \@ref(fig:3-3)

Hyphomonas neptunium \@ref(fig:5-3b)

Idiomarina loihiensis \@ref(fig:5-6)

Myxococcus xanthus \@ref(fig:2-4)

Myxococcus xanthus \@ref(fig:2-4c)

Prosthecobacter debontii \@ref(fig:2-4d)

Pseudomonas aeruginosa \@ref(fig:9-4)

Pseudomonas flexibilis \@ref(fig:6-5)

Shewanella oneidensis \@ref(fig:10-10)

Shewanella oneidensis \@ref(fig:7-1)

Sulfolobus solfataricus \@ref(fig:2-7)

Thermococcus kodakaraensis \@ref(fig:8-3)

Treponema primitia \@ref(fig:6-7a)

Vibrio cholerae \@ref(fig:10-4)


## Vesicles (periplasmic) {-}

Agrobacterium tumefaciens \@ref(fig:5-8)

Hydrogenovibrio crunogenus \@ref(fig:4-7b)

Prosthecobacter vanneervenii \@ref(fig:3-6a)


## Virus-associated pyramids {-}

Sulfolobus solfataricus \@ref(fig:10-8)

Sulfolobus solfataricus \@ref(fig:10-9)




